provider:
  name: aws
  runtime: python3.6
  profile: serverless-admin
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: elasticloadbalancing:Describe*
      Resource: "*"
    - Effect: Allow
      Action:
        - ec2:DescribeInstances
        - ec2:DescribeClassicLinkInstances
        - ec2:DescribeSecurityGroups
      Resource: "*"
    - Effect: Allow
      Action:
        - autoscaling:Describe*
        - cloudwatch:*
        - logs:*
        - sns:*
        - iam:GetPolicy
        - iam:GetPolicyVersion
        - iam:GetRole
      Resource: "*"
    - Effect: Allow
      Action: iam:CreateServiceLinkedRole
      Resource: arn:aws:iam::*:role/aws-service-role/events.amazonaws.com/AWSServiceRoleForCloudWatchEvents*
      Condition:
        StringLike:
          iam:AWSServiceName: events.amazonaws.com  
functions:
 hello:
  handler: handler.hello
  events:
       - cloudwatchEvent:
           event:
             source:
               - aws.elasticloadbalancingV2
             detail-type:
               - AWS API Call via CloudTrail
             detail:
               eventSource:
                 - elasticloadbalancing.amazonaws.com
               eventName:
                 - CreateLoadBalancer
